repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt (check)
        entry: bash -lc 'cargo fmt --all -- --check'
        language: system
        pass_filenames: false
        stages: [commit]

      - id: cargo-clippy
        name: cargo clippy (deny warnings)
        entry: bash -lc 'cargo clippy --workspace --all-targets -- -D warnings'
        language: system
        pass_filenames: false
        stages: [commit]

      # Optional: quick tests on push (can be commented if too slow)
      - id: cargo-test
        name: cargo test (quick)
        entry: bash -lc 'cargo test --workspace -q'
        language: system
        pass_filenames: false
        stages: [push]

