[build]
# Optimize for the host CPU (on Oracle ARM/Ampere this enables NEON and tuned codegen)
rustflags = ["-C", "target-cpu=native"]

# Use fast LLD linker on Linux ARM64 for much quicker LTO linking
[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
