//! Fits the BT.2100 Profile 8.4 composer (`dovi84_composer::Composer::Bt2100V1`) and reports
//! composers against the BT.2100 / BT.2408 reference. Design: docs/HLG_COMPOSER.md.
//!
//! ```text
//! fit_hlg_composer fit [--write <bt2100_v1.rs>] [--ridge <r>]
//! fit_hlg_composer report [--spec-fixed [--vectors]]
//! fit_hlg_composer rewrite-rpu <preset|bt2100> <RPU.bin>
//! fit_hlg_composer mapping <preset|bt2100>
//! fit_hlg_composer chroma-siting <preset|bt2100> <width> <height> [--every N]
//!     [--render <rgba64le>] [--mask <u8 per pixel>] [--anchor-out <csv>] [--dump-pixels <dir>]
//!     < yuv420p10le
//! ```

mod fit;
mod model;
mod report;
mod samples;
mod siting;

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{bail, Context, Result};
use dolby_vision::rpu::rpu_data_mapping::{
    DoviMMRCurve, DoviMappingMethod, DoviPolynomialCurve, DoviReshapingCurve, RpuDataMapping,
};
use dovi84_composer::Composer;

use crate::fit::{ChromaFit, LumaFit};
use crate::model::Decoder;

const DEFAULT_RIDGE: f64 = 1e-7;

fn delta_pivots(pivots: &[u16; 9]) -> [u16; 9] {
    let mut out = *pivots;
    for k in 1..9 {
        out[k] = pivots[k] - pivots[k - 1];
    }
    out
}

fn mapping_of(luma: &LumaFit, chroma: Option<&ChromaFit>) -> RpuDataMapping {
    let mut mapping = Composer::Preset.rpu_data_mapping();
    mapping.curves[0] = DoviReshapingCurve {
        num_pivots_minus2: 7,
        pivots: delta_pivots(&luma.pivots).to_vec(),
        mapping_idc: DoviMappingMethod::Polynomial,
        polynomial: Some(DoviPolynomialCurve {
            poly_order_minus1: vec![1; 8],
            linear_interp_flag: vec![],
            poly_coef_int: luma
                .coef
                .iter()
                .map(|row| row.map(|c| c.int).into())
                .collect(),
            poly_coef: luma
                .coef
                .iter()
                .map(|row| row.map(|c| c.frac).into())
                .collect(),
        }),
        mmr: None,
    };
    if let Some(chroma) = chroma {
        for component in 0..2 {
            let coef = &chroma.coef[component];
            let orders = |pick: fn(fit::Fixed) -> i64| -> Vec<[i64; 7]> {
                (0..3)
                    .map(|o| std::array::from_fn(|t| pick(coef[1 + o * 7 + t])))
                    .collect()
            };
            let ints = orders(|c| c.int);
            let fracs = orders(|c| c.frac as i64);
            mapping.curves[component + 1] = DoviReshapingCurve {
                num_pivots_minus2: 0,
                pivots: vec![0, 1023],
                mapping_idc: DoviMappingMethod::MMR,
                polynomial: None,
                mmr: Some(DoviMMRCurve {
                    mmr_order_minus1: vec![2],
                    mmr_constant_int: vec![coef[0].int],
                    mmr_constant: vec![coef[0].frac],
                    mmr_coef_int: vec![ints.iter().map(|&row| row.into()).collect()],
                    mmr_coef: vec![fracs
                        .iter()
                        .map(|&row| row.map(|f| f as u64).into())
                        .collect()],
                }),
            };
        }
    }
    mapping
}

fn constants_file(luma: &LumaFit, chroma: &ChromaFit, ridge: f64) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by tools/fit_hlg_composer (`fit --write`, ridge {ridge:e}); do not edit.\n\
         // Fitted to the BT.2100 / BT.2408 1000-nit HLG-to-PQ conversion with neutrals kept\n\
         // neutral (docs/HLG_COMPOSER.md). Coefficients are int + frac / 2^23.\n"
    );
    let _ = writeln!(
        out,
        "/// Luma pivots, delta-coded 10-bit codes (absolute: {:?}).",
        luma.pivots
    );
    let _ = writeln!(
        out,
        "pub const LUMA_PIVOTS: [u16; 9] = {:?};",
        delta_pivots(&luma.pivots)
    );
    let ints: Vec<[i64; 3]> = luma.coef.iter().map(|row| row.map(|c| c.int)).collect();
    let fracs: Vec<[u64; 3]> = luma.coef.iter().map(|row| row.map(|c| c.frac)).collect();
    let _ = writeln!(out, "pub const LUMA_POLY_INT: [[i64; 3]; 8] = {ints:?};");
    let _ = writeln!(out, "pub const LUMA_POLY_FRAC: [[u64; 3]; 8] = {fracs:?};");
    let constants_int = chroma.coef.map(|c| c[0].int);
    let constants_frac = chroma.coef.map(|c| c[0].frac);
    let _ = writeln!(
        out,
        "/// Chroma MMR (Cb, Cr): constant, then [y, u, v, yu, yv, uv, yuv] for powers 1..=3."
    );
    let _ = writeln!(
        out,
        "pub const MMR_CONSTANT_INT: [i64; 2] = {constants_int:?};"
    );
    let _ = writeln!(
        out,
        "pub const MMR_CONSTANT_FRAC: [u64; 2] = {constants_frac:?};"
    );
    let pick_int = chroma.coef.map(|c| -> [[i64; 7]; 3] {
        std::array::from_fn(|o| std::array::from_fn(|t| c[1 + o * 7 + t].int))
    });
    let pick_frac = chroma.coef.map(|c| -> [[u64; 7]; 3] {
        std::array::from_fn(|o| std::array::from_fn(|t| c[1 + o * 7 + t].frac))
    });
    let _ = writeln!(
        out,
        "pub const MMR_COEF_INT: [[[i64; 7]; 3]; 2] = {pick_int:?};"
    );
    let _ = writeln!(
        out,
        "pub const MMR_COEF_FRAC: [[[u64; 7]; 3]; 2] = {pick_frac:?};"
    );
    out
}

fn run_fit(write: Option<&str>, ridge: f64) -> Result<()> {
    let luma = fit::fit_luma();
    println!(
        "luma: pivots {:?}, max error before quantization {:.3} 12-bit codes",
        luma.pivots, luma.max_error
    );
    let luma_only = Decoder::new(&mapping_of(&luma, None));
    let luma_term: Vec<f64> = (0..1024_u16)
        .map(|code| luma_only.luma_term(code))
        .collect();
    let chroma = fit::fit_chroma(&luma_term, ridge);
    for (name, residuals) in ["Cb", "Cr"].iter().zip(chroma.constraint_residuals) {
        println!(
            "{name}: neutral constraint residuals after quantization {:?}",
            residuals.map(|r| format!("{r:.1e}"))
        );
    }
    let max_abs = chroma
        .coef
        .iter()
        .flatten()
        .map(|c| c.value().abs())
        .fold(0.0, f64::max);
    println!("chroma: largest |coefficient| {max_abs:.3}");

    let mapping = mapping_of(&luma, Some(&chroma));
    let fitted = report::evaluate("fitted (bt2100)", &mapping);
    let preset = report::evaluate("preset", &Composer::Preset.rpu_data_mapping());
    print!("{}\n{}", preset.text, fitted.text);
    let mut all = true;
    for (line, pass) in report::acceptance(&fitted, &preset) {
        println!("{} {line}", if pass { "PASS" } else { "FAIL" });
        all &= pass;
    }
    if let Some(path) = write {
        std::fs::write(path, constants_file(&luma, &chroma, ridge))
            .with_context(|| format!("writing {path}"))?;
        // Format like the rest of the crate, so a refit diffs only in the values.
        let formatted = std::process::Command::new("rustfmt")
            .args(["--edition", "2021", path])
            .status()
            .with_context(|| format!("running rustfmt on {path}"))?;
        if !formatted.success() {
            bail!("rustfmt failed on {path}");
        }
        println!("wrote {path}");
    }
    if !all {
        println!("acceptance: not all criteria pass");
    }
    Ok(())
}

/// `report --spec-fixed`: the criteria of docs/HLG_COMPOSER.md section 6 measured through the
/// spec's fixed-point composer (ETSI GS CCM 001 §5.4.2.2–5.4.2.3) on flat fields, as the
/// analyzer will decode once it follows the spec. Items 1, 2, 3 and 6 decide for bt2100; 4, 4b
/// and 5 are reported.
fn run_spec_report(vectors: bool) -> Result<()> {
    let preset = siting::Variants::new(&Composer::Preset.rpu_data_mapping())?;
    let fitted = siting::Variants::new(&Composer::Bt2100V1.rpu_data_mapping())?;
    let preset_eval = report::evaluate_with("preset, spec fixed point", &preset);
    let fitted_eval = report::evaluate_with("bt2100-v1, spec fixed point", &fitted);
    print!("{}\n{}", preset_eval.text, fitted_eval.text);

    println!("\nneutral composed chroma (Cb16 − 32768, Cr16 − 32768) over codes 64..=1019:");
    for (name, variants) in [("preset", &preset), ("bt2100-v1", &fitted)] {
        let mut runs: Vec<(u16, u16, [i32; 2])> = Vec::new();
        for code in 64..=1019_u16 {
            let delta = variants
                .flat_chroma16(code, 512, 512)
                .map(|c| i32::from(c) - 32768);
            match runs.last_mut() {
                Some((_, last, d)) if *d == delta => *last = code,
                _ => runs.push((code, code, delta)),
            }
        }
        println!("  {name}: {} runs", runs.len());
        for (first, last, delta) in runs.iter().take(40) {
            println!("    {first:4}..={last:4}: ({:+}, {:+})", delta[0], delta[1]);
        }
        if runs.len() > 40 {
            println!("    … {} more runs", runs.len() - 40);
        }
    }

    let clamp_points = |variants: &siting::Variants| {
        [0_u16, 64, 940, 1019].map(|code| f64::from(variants.flat_max_rgb(code, 512, 512)) * 4095.0)
    };
    let mut rows = Vec::new();
    for (line, pass) in report::acceptance(&fitted_eval, &preset_eval) {
        let deciding = ["1.", "2.", "3."].iter().any(|p| line.starts_with(p));
        rows.push((line, pass, deciding));
    }
    rows.push((
        format!(
            "2 (near black). neutral luma error over 64..=100 {:.2} <= 1.0",
            fitted_eval.near_black_luma_error_max
        ),
        fitted_eval.near_black_luma_error_max <= 1.0,
        true,
    ));
    let [black, black64, white940, white1019] = clamp_points(&fitted);
    rows.push((
        format!(
            "6. source clamp: codes 0, 64 -> {black:.2}, {black64:.2} (62); codes 940, 1019 -> \
             {white940:.2}, {white1019:.2} (3079)"
        ),
        black.round() == 62.0
            && black64.round() == 62.0
            && white940.round() == 3079.0
            && white1019.round() == 3079.0,
        true,
    ));
    let [p0, p64, p940, p1019] = clamp_points(&preset);
    println!(
        "\npreset source clamp (information): codes 0, 64, 940, 1019 -> {p0:.2}, {p64:.2}, \
         {p940:.2}, {p1019:.2}"
    );

    println!("\nbt2100-v1 through the spec composer (docs/HLG_COMPOSER.md section 6):");
    let mut stop = false;
    for (line, pass, deciding) in &rows {
        let verdict = if *pass { "PASS" } else { "FAIL" };
        let role = if *deciding { "decides" } else { "reported" };
        println!("{verdict} ({role}) {line}");
        stop |= *deciding && !*pass;
    }
    println!(
        "{}",
        if stop {
            "STOP: a deciding criterion fails under the spec composer"
        } else {
            "all deciding criteria pass under the spec composer"
        }
    );

    if vectors {
        print_spec_vectors(&preset, &fitted);
    }
    Ok(())
}

/// Values the analyzer's spec decode is pinned to (docs/HLG_COMPOSER.md section 9).
fn print_spec_vectors(preset: &siting::Variants, fitted: &siting::Variants) {
    const LUMA_CODES: [u16; 12] = [0, 63, 64, 200, 304, 502, 721, 896, 940, 942, 1019, 1023];
    const CHROMA: [(u16, u16, u16); 8] = [
        (64, 512, 512),
        (721, 512, 512),
        (940, 512, 512),
        (502, 64, 960),
        (502, 960, 64),
        (300, 64, 64),
        (900, 960, 960),
        (1019, 0, 1023),
    ];
    for (name, variants) in [("preset", preset), ("bt2100-v1", fitted)] {
        println!("\nvectors {name}:");
        for code in LUMA_CODES {
            println!("  luma16({code}) = {}", variants.luma16(code));
        }
        for (y, cb, cr) in CHROMA {
            let [c0, c1] = variants.flat_chroma16(y, cb, cr);
            let max_rgb = variants.flat_max_rgb(y, cb, cr);
            println!(
                "  flat ({y}, {cb}, {cr}): chroma16 ({c0}, {c1}), max_rgb 0x{:08x} ({:.3} codes)",
                max_rgb.to_bits(),
                f64::from(max_rgb) * 4095.0
            );
        }
    }
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("fit") => {
            let mut write = None;
            let mut ridge = DEFAULT_RIDGE;
            let mut rest = args[1..].iter();
            while let Some(arg) = rest.next() {
                match arg.as_str() {
                    "--write" => write = rest.next().map(String::as_str),
                    "--ridge" => ridge = rest.next().context("--ridge needs a value")?.parse()?,
                    other => bail!("unknown argument {other}"),
                }
            }
            run_fit(write, ridge)
        }
        Some("report") if args.get(1).map(String::as_str) == Some("--spec-fixed") => {
            match args.get(2).map(String::as_str) {
                None => run_spec_report(false),
                Some("--vectors") => run_spec_report(true),
                Some(other) => bail!("unknown argument {other}"),
            }
        }
        Some("report") => {
            let preset = report::evaluate("preset", &Composer::Preset.rpu_data_mapping());
            let fitted = report::evaluate(
                "bt2100-v1 (dovi84_composer)",
                &Composer::Bt2100V1.rpu_data_mapping(),
            );
            print!("{}\n{}", preset.text, fitted.text);
            for (line, pass) in report::acceptance(&fitted, &preset) {
                println!("{} {line}", if pass { "PASS" } else { "FAIL" });
            }
            Ok(())
        }
        Some("rewrite-rpu") => {
            let composer = match args.get(1).map(String::as_str) {
                Some("preset") => Composer::Preset,
                Some("bt2100") => Composer::Bt2100V1,
                _ => bail!("rewrite-rpu <preset|bt2100> <RPU.bin>"),
            };
            let path = args.get(2).context("rewrite-rpu <preset|bt2100> <RPU.bin>")?;
            let frames = dovi84_composer::rewrite_rpu_file(Path::new(path), composer)?;
            println!(
                "{path}: {frames} frames now carry {}",
                composer.luminance_mapping()
            );
            Ok(())
        }
        Some("mapping") => {
            // The sidecar `luminance_mapping` the analyzer writes for a composer, so scripts
            // need not repeat the names.
            let composer = match args.get(1).map(String::as_str) {
                Some("preset") => Composer::Preset,
                Some("bt2100") => Composer::Bt2100V1,
                _ => bail!("mapping <preset|bt2100>"),
            };
            println!("{}", composer.luminance_mapping());
            Ok(())
        }
        Some("chroma-siting") => siting::run(&args[1..]),
        _ => bail!("usage: fit_hlg_composer fit [--write <file>] [--ridge <r>] | report [--spec-fixed [--vectors]] | rewrite-rpu <preset|bt2100> <RPU.bin> | mapping <preset|bt2100> | chroma-siting <preset|bt2100> <width> <height> [options]"),
    }
}
