//! Fits the BT.2100 Profile 8.4 composer (`dovi84_composer::Composer::Bt2100V1`) and reports
//! composers against the BT.2100 / BT.2408 reference. Design: docs/HLG_COMPOSER.md.
//!
//! ```text
//! fit_hlg_composer fit [--write <bt2100_v1.rs>] [--ridge <r>]
//! fit_hlg_composer report
//! fit_hlg_composer rewrite-rpu <preset|bt2100> <RPU.bin>
//! fit_hlg_composer chroma-siting <preset|bt2100> <width> <height> [--every N]
//!     [--render <rgba64le>] [--mask <u8 per pixel>] [--anchor-out <csv>] < yuv420p10le
//! ```

mod fit;
mod model;
mod report;
mod samples;
mod siting;

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{bail, Context, Result};
use dolby_vision::rpu::rpu_data_mapping::{
    DoviMMRCurve, DoviMappingMethod, DoviPolynomialCurve, DoviReshapingCurve, RpuDataMapping,
};
use dovi84_composer::Composer;

use crate::fit::{ChromaFit, LumaFit};
use crate::model::Decoder;

const DEFAULT_RIDGE: f64 = 1e-7;

fn delta_pivots(pivots: &[u16; 9]) -> [u16; 9] {
    let mut out = *pivots;
    for k in 1..9 {
        out[k] = pivots[k] - pivots[k - 1];
    }
    out
}

fn mapping_of(luma: &LumaFit, chroma: Option<&ChromaFit>) -> RpuDataMapping {
    let mut mapping = Composer::Preset.rpu_data_mapping();
    mapping.curves[0] = DoviReshapingCurve {
        num_pivots_minus2: 7,
        pivots: delta_pivots(&luma.pivots).to_vec(),
        mapping_idc: DoviMappingMethod::Polynomial,
        polynomial: Some(DoviPolynomialCurve {
            poly_order_minus1: vec![1; 8],
            linear_interp_flag: vec![],
            poly_coef_int: luma
                .coef
                .iter()
                .map(|row| row.map(|c| c.int).into())
                .collect(),
            poly_coef: luma
                .coef
                .iter()
                .map(|row| row.map(|c| c.frac).into())
                .collect(),
        }),
        mmr: None,
    };
    if let Some(chroma) = chroma {
        for component in 0..2 {
            let coef = &chroma.coef[component];
            let orders = |pick: fn(fit::Fixed) -> i64| -> Vec<[i64; 7]> {
                (0..3)
                    .map(|o| std::array::from_fn(|t| pick(coef[1 + o * 7 + t])))
                    .collect()
            };
            let ints = orders(|c| c.int);
            let fracs = orders(|c| c.frac as i64);
            mapping.curves[component + 1] = DoviReshapingCurve {
                num_pivots_minus2: 0,
                pivots: vec![0, 1023],
                mapping_idc: DoviMappingMethod::MMR,
                polynomial: None,
                mmr: Some(DoviMMRCurve {
                    mmr_order_minus1: vec![2],
                    mmr_constant_int: vec![coef[0].int],
                    mmr_constant: vec![coef[0].frac],
                    mmr_coef_int: vec![ints.iter().map(|&row| row.into()).collect()],
                    mmr_coef: vec![fracs
                        .iter()
                        .map(|&row| row.map(|f| f as u64).into())
                        .collect()],
                }),
            };
        }
    }
    mapping
}

fn constants_file(luma: &LumaFit, chroma: &ChromaFit, ridge: f64) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by tools/fit_hlg_composer (`fit --write`, ridge {ridge:e}); do not edit.\n\
         // Fitted to the BT.2100 / BT.2408 1000-nit HLG-to-PQ conversion with neutrals kept\n\
         // neutral (docs/HLG_COMPOSER.md). Coefficients are int + frac / 2^23.\n"
    );
    let _ = writeln!(
        out,
        "/// Luma pivots, delta-coded 10-bit codes (absolute: {:?}).",
        luma.pivots
    );
    let _ = writeln!(
        out,
        "pub const LUMA_PIVOTS: [u16; 9] = {:?};",
        delta_pivots(&luma.pivots)
    );
    let ints: Vec<[i64; 3]> = luma.coef.iter().map(|row| row.map(|c| c.int)).collect();
    let fracs: Vec<[u64; 3]> = luma.coef.iter().map(|row| row.map(|c| c.frac)).collect();
    let _ = writeln!(out, "pub const LUMA_POLY_INT: [[i64; 3]; 8] = {ints:?};");
    let _ = writeln!(out, "pub const LUMA_POLY_FRAC: [[u64; 3]; 8] = {fracs:?};");
    let constants_int = chroma.coef.map(|c| c[0].int);
    let constants_frac = chroma.coef.map(|c| c[0].frac);
    let _ = writeln!(
        out,
        "/// Chroma MMR (Cb, Cr): constant, then [y, u, v, yu, yv, uv, yuv] for powers 1..=3."
    );
    let _ = writeln!(
        out,
        "pub const MMR_CONSTANT_INT: [i64; 2] = {constants_int:?};"
    );
    let _ = writeln!(
        out,
        "pub const MMR_CONSTANT_FRAC: [u64; 2] = {constants_frac:?};"
    );
    let pick_int = chroma.coef.map(|c| -> [[i64; 7]; 3] {
        std::array::from_fn(|o| std::array::from_fn(|t| c[1 + o * 7 + t].int))
    });
    let pick_frac = chroma.coef.map(|c| -> [[u64; 7]; 3] {
        std::array::from_fn(|o| std::array::from_fn(|t| c[1 + o * 7 + t].frac))
    });
    let _ = writeln!(
        out,
        "pub const MMR_COEF_INT: [[[i64; 7]; 3]; 2] = {pick_int:?};"
    );
    let _ = writeln!(
        out,
        "pub const MMR_COEF_FRAC: [[[u64; 7]; 3]; 2] = {pick_frac:?};"
    );
    out
}

fn run_fit(write: Option<&str>, ridge: f64) -> Result<()> {
    let luma = fit::fit_luma();
    println!(
        "luma: pivots {:?}, max error before quantization {:.3} 12-bit codes",
        luma.pivots, luma.max_error
    );
    let luma_only = Decoder::new(&mapping_of(&luma, None));
    let luma_term: Vec<f64> = (0..1024_u16)
        .map(|code| luma_only.luma_term(code))
        .collect();
    let chroma = fit::fit_chroma(&luma_term, ridge);
    for (name, residuals) in ["Cb", "Cr"].iter().zip(chroma.constraint_residuals) {
        println!(
            "{name}: neutral constraint residuals after quantization {:?}",
            residuals.map(|r| format!("{r:.1e}"))
        );
    }
    let max_abs = chroma
        .coef
        .iter()
        .flatten()
        .map(|c| c.value().abs())
        .fold(0.0, f64::max);
    println!("chroma: largest |coefficient| {max_abs:.3}");

    let mapping = mapping_of(&luma, Some(&chroma));
    let fitted = report::evaluate("fitted (bt2100)", &mapping);
    let preset = report::evaluate("preset", &Composer::Preset.rpu_data_mapping());
    print!("{}\n{}", preset.text, fitted.text);
    let mut all = true;
    for (line, pass) in report::acceptance(&fitted, &preset) {
        println!("{} {line}", if pass { "PASS" } else { "FAIL" });
        all &= pass;
    }
    if let Some(path) = write {
        std::fs::write(path, constants_file(&luma, &chroma, ridge))
            .with_context(|| format!("writing {path}"))?;
        // Format like the rest of the crate, so a refit diffs only in the values.
        let formatted = std::process::Command::new("rustfmt")
            .args(["--edition", "2021", path])
            .status()
            .with_context(|| format!("running rustfmt on {path}"))?;
        if !formatted.success() {
            bail!("rustfmt failed on {path}");
        }
        println!("wrote {path}");
    }
    if !all {
        println!("acceptance: not all criteria pass");
    }
    Ok(())
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("fit") => {
            let mut write = None;
            let mut ridge = DEFAULT_RIDGE;
            let mut rest = args[1..].iter();
            while let Some(arg) = rest.next() {
                match arg.as_str() {
                    "--write" => write = rest.next().map(String::as_str),
                    "--ridge" => ridge = rest.next().context("--ridge needs a value")?.parse()?,
                    other => bail!("unknown argument {other}"),
                }
            }
            run_fit(write, ridge)
        }
        Some("report") => {
            let preset = report::evaluate("preset", &Composer::Preset.rpu_data_mapping());
            let fitted = report::evaluate(
                "bt2100-v1 (dovi84_composer)",
                &Composer::Bt2100V1.rpu_data_mapping(),
            );
            print!("{}\n{}", preset.text, fitted.text);
            for (line, pass) in report::acceptance(&fitted, &preset) {
                println!("{} {line}", if pass { "PASS" } else { "FAIL" });
            }
            Ok(())
        }
        Some("rewrite-rpu") => {
            let composer = match args.get(1).map(String::as_str) {
                Some("preset") => Composer::Preset,
                Some("bt2100") => Composer::Bt2100V1,
                _ => bail!("rewrite-rpu <preset|bt2100> <RPU.bin>"),
            };
            let path = args.get(2).context("rewrite-rpu <preset|bt2100> <RPU.bin>")?;
            let frames = dovi84_composer::rewrite_rpu_file(Path::new(path), composer)?;
            println!(
                "{path}: {frames} frames now carry {}",
                composer.luminance_mapping()
            );
            Ok(())
        }
        Some("chroma-siting") => siting::run(&args[1..]),
        _ => bail!("usage: fit_hlg_composer fit [--write <file>] [--ridge <r>] | report | rewrite-rpu <preset|bt2100> <RPU.bin> | chroma-siting <preset|bt2100> <width> <height> [options]"),
    }
}
